kind: PersistentVolume
apiVersion: v1
metadata:
  name: pgadmin
  labels:
    app: pgadmin
    version: latest
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    type: DirectoryOrCreate
    path: /run/desktop/mnt/host/c/VolumesDisk/pgadmin