kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgadmin
  namespace: folder4study
  labels:
    app: pgadmin
    version: latest
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi