apiVersion: v1
kind: Service
metadata:
  name: service-pgadmin
  namespace: folder4study
  labels:
    app: pgadmin
    version: latest
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
  ports:
    - name: port
      port: 80
      targetPort: port